"""
Built-in presets, as changes to the factory defaults (config_defaults.py).

Generated by tools/publish_presets.py from the maintainer's saved presets:
change them in the app, save them, and run it (the release build does).
"""
from typing import Any, Dict

BUILTIN_PRESETS: Dict[str, Dict[str, Any]] = {
    "Facing": {
        "tracking.view_mode": "facing",
        "calibration.rotation_offset_deg.left": [0.0, 0.0, -90.0],
        "calibration.rotation_offset_deg.right": [0.0, 0.0, 90.0],
        "camera.source_mirrored": True,
        "calibration.position_offset": [0.0, 0.0, -0.2],
        "calibration.filter.position.beta": 1.41,
    },
    "POV": {
        "tracking.view_mode": "pov",
        "calibration.rotation_offset_deg.left": [0.0, -40.0, -90.0],
        "calibration.rotation_offset_deg.right": [0.0, 40.0, 90.0],
        "calibration.steady_hand_size": True,
        "calibration.rebuild_hand": True,
        "calibration.position_offset": [0.0, 0.1, 0.0],
        "calibration.filter.mode": "ema",
    },
    "POV Pointer": {
        "tracking.view_mode": "pov",
        "calibration.rotation_offset_deg.left": [-31.0, 24.0, -57.0],
        "calibration.rotation_offset_deg.right": [-31.0, -24.0, 57.0],
        "calibration.steady_hand_size": True,
        "calibration.rebuild_hand": True,
        "calibration.position_offset": [0.0, 0.1, 0.0],
        "calibration.filter.mode": "ema",
    },
}
