"""
Make the presets saved in a config.json the app's built-in presets.

Every preset saved in the file (the built-in ones as changed there, and the
user's own) is written to builtin_presets.py as changes to the factory
defaults, so the next build ships them. Unsaved changes are left out. Saved
presets that now match their built-in version are dropped from the file, so
they keep following future defaults.

    python tools/publish_presets.py [config.json] [--check]

--check only says whether builtin_presets.py would change (exit code 1 if so).
"""
import argparse
import copy
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import presets  # noqa: E402
from config_defaults import DEFAULT_CONFIG  # noqa: E402

OUTPUT = os.path.join(ROOT, "builtin_presets.py")
HEADER = '''"""
Built-in presets, as changes to the factory defaults (config_defaults.py).

Generated by tools/publish_presets.py from the maintainer's saved presets:
change them in the app, save them, and run it (the release build does).
"""
from typing import Any, Dict

'''
# Written out even when they match the factory defaults: they say what a preset is
ALWAYS = ("tracking.view_mode", "calibration.rotation_offset_deg.left", "calibration.rotation_offset_deg.right")


def built_in(config):
    """Each saved preset as {dotted key: value} changes to the factory defaults."""
    factory = presets.snapshot(DEFAULT_CONFIG)
    builtin = [name for name in presets.names(config) if presets.is_builtin(name)]
    user = [name for name in presets.names(config) if not presets.is_builtin(name)]
    result = {}
    for name in builtin + user:
        values = presets.values(config, name)
        changed = {key: values[key] for key in ALWAYS}
        changed.update({key: value for key, value in values.items() if key not in ALWAYS and factory.get(key) != value})
        result[name] = changed
    return result


def literal(value):
    return json.dumps(value, ensure_ascii=False) if isinstance(value, str) else repr(value)


def render(builtin):
    lines = [f"{HEADER}BUILTIN_PRESETS: Dict[str, Dict[str, Any]] = {{"]
    for name, values in builtin.items():
        lines.append(f"    {literal(name)}: {{")
        lines += [f"        {literal(key)}: {literal(value)}," for key, value in values.items()]
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def prune(raw, builtin):
    """Drop saved presets that match the new built-in ones. Returns their names."""
    factory = presets.snapshot(DEFAULT_CONFIG)
    dropped = []
    for name, saved in list(raw.get("presets", {}).items()):
        shipped = {**factory, **builtin.get(name, {})}
        if name in builtin and all(shipped.get(key) == value for key, value in saved.items()):
            raw["presets"].pop(name)
            dropped.append(name)
    return dropped


def main():
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("config", nargs="?", default=os.path.join(ROOT, "config.json"))
    parser.add_argument("--check", action="store_true", help="only report whether builtin_presets.py would change")
    args = parser.parse_args()

    with open(args.config, encoding="utf-8") as f:
        raw = json.load(f)
    config = copy.deepcopy(raw)
    presets.migrate(config)
    presets.fill_new_settings(config)
    if presets.is_modified(config):
        print(f"note: preset {presets.active(config)} has unsaved changes; they are left out")

    builtin = built_in(config)
    for name in (presets.DEFAULT_PRESET, *presets.MODE_PRESETS.values()):
        if name not in builtin:
            sys.exit(f"error: built-in preset {name} is missing")
    text = render(builtin)
    with open(OUTPUT, encoding="utf-8") as f:
        changed = f.read() != text
    if args.check:
        print("builtin_presets.py would change" if changed else "builtin_presets.py is up to date")
        sys.exit(1 if changed else 0)

    if changed:
        with open(OUTPUT, "w", encoding="utf-8") as f:
            f.write(text)
    print("built-in presets:", ", ".join(builtin), "(updated)" if changed else "(unchanged)")
    dropped = prune(raw, builtin)
    if dropped:
        with open(args.config, "w") as f:
            json.dump(raw, f, indent=2)
            f.write("\n")
        print("now built in, removed from", os.path.basename(args.config) + ":", ", ".join(dropped))


if __name__ == "__main__":
    main()
